# Generated by Django 5.2.4 on 2025-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahira_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='administration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الإدارة'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المعهد'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='job_grade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الدرجة الوظيفية'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة'),
        ),
    ]
