# Generated by Django 5.2.4 on 2025-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahira_training', '0002_teacher_administration_teacher_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان إقامة البرنامج التدريبي'),
        ),
    ]
