# Generated by Django 5.2.4 on 2025-07-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahira_training', '0003_trainingprogram_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم القاعة'),
        ),
    ]
